spring:
  profiles:
    active: zpcdev # 指定application文件
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/relocateWeb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true

relocate:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    back-secret-key: ahut
    # 设置jwt过期时间
    back-ttl: 72000000
    # 设置前端传递过来的令牌名称
    back-token-name: token

    front-secret-key: ahut
    front-ttl: 72000000
    front-token-name: authentication

# 日志配置
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahut.entity  # 类型别名所在包
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl